[package]
name = "vm_math"
version = "0.1.0"
authors = ["Andrey Kabylin <andrey@kabylin.ru>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
vm_buffers = { git = "https://github.com/tech-paws/vm_buffers.git" }
